# -*- coding: utf-8 -*-
"""gl.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18a_OSVkD66VHxWIph402diwOE2BAYLp1
"""

import subprocess
import sys
pr = []
# open a subprocess with two-way communication
# if simply `"./stats-sum"` doesn't work, you can try
# passing the array `["python3", "./stats-sum"]`
for st in sys.argv[:1]:
  pr.append(my_subprocess = subprocess.Popen("./stats_%s.py" % (st),
    stdin=subprocess.PIPE, stdout=subprocess.PIPE))

for l in sys.stdin:
  inputs = l.strip().split('\t')
  # need to encode the string, because we communicate binary
  # it needs a linebreak, because that is how we separate records
  for x, my_subprocess in zip(inputs, pr):
    my_subprocess.stdin.write("{}\n".format(x).encode('utf-8'))

# inform the subprocess that is the end of input
[my_subprocess.stdin.close() for my_subprocess in pr]

# read the binary result, and decode
# don't double the newlines
[print(my_subprocess.stdout.read().decode('utf-8'), end='') for my_subprocess in pr]