# -*- coding: utf-8 -*-
"""stats-median.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18a_OSVkD66VHxWIph402diwOE2BAYLp1
"""

#!/usr/bin/python3
import sys
sum = 0
count = 0
l = []
for line in sys.stdin:
  l.append(int(line))
  count += 1
l = sorted(l)
if (count%2 == 0):
  print(l[count/2])
else:
  print((l[(count -1)/2] + l[(count +1)/2])/2)