# -*- coding: utf-8 -*-
"""stats-mean.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18a_OSVkD66VHxWIph402diwOE2BAYLp1
"""

#!/usr/bin/python3
import sys
sum = 0
count = 0
for line in sys.stdin:
  sum += int(line)
  count += 1
if count != 0:
  print(sum/count)
else:
  print('0')