# -*- coding: utf-8 -*-
"""stats-mad.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18a_OSVkD66VHxWIph402diwOE2BAYLp1
"""

#!/usr/bin/python3

import sys
import statistics

s= []
for line in sys.stdin:
  s.append(int(line))

m = statistics.median(s)
s1 = []

for el in s:
  s1.append(abs(el-m))
  
print(statistics.median(s1))